abi <abi/4.0>,

profile "test-mount-tmpfs-rw" flags=(attach_disconnected,mediate_deleted) {
  # See parser/mount.cc for implementation details.
  mount fstype=tmpfs options=(rw) none -> /tmp/**,

  capability sys_admin,

  # Remaining permissions required to run mount. We are _not_ using any
  # abstractions to avoid getting confused by what is really needed. This
  # approach helps both in understanding the test and in helping shape mount
  # profiles generated by snapd.
  /etc/ld.so.cache r,
  /etc/locale.alias r,
  /proc/*/mountinfo r,
  /proc/*/mounts r,
  /proc/filesystems r,
  /run/mount/utab r,
  /usr/lib/*-linux-gnu/gconv/gconv-modules.cache r,
  /usr/lib/*-linux-gnu/libblkid.so.* rm,
  /usr/lib/*-linux-gnu/libc.so.* rm,
  /usr/lib/*-linux-gnu/libmount.so.* rm,
  /usr/lib/*-linux-gnu/libpcre2-*.so.* rm,
  /usr/lib/*-linux-gnu/libselinux.so.* rm,
  /usr/lib/locale/C.utf8/LC_ADDRESS r,
  /usr/lib/locale/C.utf8/LC_COLLATE r,
  /usr/lib/locale/C.utf8/LC_CTYPE r,
  /usr/lib/locale/C.utf8/LC_IDENTIFICATION r,
  /usr/lib/locale/C.utf8/LC_MEASUREMENT r,
  /usr/lib/locale/C.utf8/LC_MESSAGES/ r,
  /usr/lib/locale/C.utf8/LC_MESSAGES/SYS_LC_MESSAGES r,
  /usr/lib/locale/C.utf8/LC_MONETARY r,
  /usr/lib/locale/C.utf8/LC_NAME r,
  /usr/lib/locale/C.utf8/LC_NUMERIC r,
  /usr/lib/locale/C.utf8/LC_PAPER r,
  /usr/lib/locale/C.utf8/LC_TELEPHONE r,
  /usr/lib/locale/C.utf8/LC_TIME r,
  /usr/lib/locale/locale-archive r,
}
